### ISSUE TITLE
Keyboard navigation support

### ISSUE THREAD

**Issue by raphaelbastide** [garris/TremulaJS#23]
This could be really helpful!

**Comment by garris** [comment]
Thanks for the suggestion!   This is something that would be very easy for you to implement on your own.  TremulaJS has an `.easeTo()` method.  Below is an example from the demo which uses button click events but you can swap out the click events for keydown events and wire them up similarly... 

```
var s = tremula.Grid;
$(".tailScroll").click(function() {

    //TremulaJS wants to know where you touched the stream so here we are just setting that parameter to the middle of the screen.  (This is mostly for item-easing behavior).
    s.setLastTouchOrigin(s.gridDims[s.si]/2);

    //Here we are scrolling from where we are to half the viewport width over 800ms.
    s.easeTo(s.getScrollPos()-(s.getScrollViewDim()*.50),800)
})

```
