### ISSUE TITLE
No loading indicator

### ISSUE THREAD

**Issue by xixixao** [garris/TremulaJS#25]
The demo website loads after quite a while in FF and stays blank since there's no loading indicator.

**Comment by tehbeard** [comment]
Preferably with an explanation that it's pulling the images from art.com or just swap to loading several local images, with an option/second demo page to show this style of large image galleries.

**Comment by garris** [comment]
Thanks for the suggestion. There is support for loading states (even though I didn't implement thobbers in the demo).  You can see this in action on [art.com here](http://www.art.com/discover/keyword--gogh/posters.htm?searchstring=GOGH#!/m=discover&r=_&k=gogh&c=_&i=_&p=_&t=gogh&cl=_)...  

Feel free to implement yourself on the demo and send me a PR -- I'd be happy to pull that in.  Cheers, GS
