### ISSUE TITLE
Examples of using TremulaJS with a local datasource rather than Flickr?

### ISSUE THREAD

**Issue by garris** [garris/TremulaJS#30]
I've gotten a few of these questions on twitter and email.  Thought I'd add the answer here...

A:  TremulaJS is happy to run locally with local data.  To see an example, do an `npm install` on the `./tremulajs/` directory then open the `./tremulajs/test.html` file.  There are multiple test data files in there which are used for testing the app ‘locally'.

Another approach is to just stub out a simple JSON object in your html page.  Then point to that JSON data instead of doing an ajax call.  Hopefully that will help.  Please post an issue with specific questions. 

Thanks!

**Comment by paxperscientiam** [comment]
Hi Garris, thanks for responding on Twitter and here on GitHub. I have no trouble running the test on my local server; however, I have no idea what I am supposed to discern from the wall of data vis-à-vis loading local data.

I'm currently reviewing index and index-dev.

**Comment by garris** [comment]
Ok, here is a gist example...

https://gist.github.com/garris/afebec8e31f5a193aa1b

**Comment by paxperscientiam** [comment]
Thank you for this, garris! I will report back with my results. Seriously, I appreciate you taking the time to help me with this.

**Comment by garris** [comment]
:+1:

**Comment by paxperscientiam** [comment]
Hi garris, so far I've it basically working. That is, I've been able to get Tremula displaying local images. I've hit a snag though. Does Tremula have a built in mechanism for serving (local) images implicitly? That is, must I provide an explicit reference to each image I'd like to display? It seems that I have to feed Tremula a JSON object. This is simple enough with a handful of images -- but what if I have hundreds of local images to display?

EDIT: Perhaps there's a way to dynamically generate the required JSON by feeding the directory path to some function?

**Comment by garris** [comment]
Hi Chris, I am not 100% sure I understand your question.  Could you maybe describe an example use-case...

**Comment by paxperscientiam** [comment]
Hi garris, allow to clarify.

var data = [
     {"id":"14770557605","owner":"77358520@N00","secret":"87c851194c","server":"5591","farm":6,"title":"Paris","ispublic":1,"isfriend":0,"isfamily":0,"url_n":"https://farm6.staticflickr.com/5591/14770557605_87c851194c_n.jpg","height_n":"320","width_n":212},
  {"id":"14770224262","owner":"77358520@N00","secret":"398cbf9839","server":"3858","farm":4,"title":"Paris","ispublic":1,"isfriend":0,"isfamily":0,"url_n":"https://farm4.staticflickr.com/3858/14770224262_398cbf9839_n.jpg","height_n":"320","width_n":240},
  {"id":"14770557605","owner":"77358520@N00","secret":"87c851194c","server":"5591","farm":6,"title":"Paris","ispublic":1,"isfriend":0,"isfamily":0,"url_n":"https://farm6.staticflickr.com/5591/14770557605_87c851194c_n.jpg","height_n":"320","width_n":212},
  {"id":"14770224262","owner":"77358520@N00","secret":"398cbf9839","server":"3858","farm":4,"title":"Paris","ispublic":1,"isfriend":0,"isfamily":0,"url_n":"https://farm4.staticflickr.com/3858/14770224262_398cbf9839_n.jpg","height_n":"320","width_n":240},
   {"id":"14768250614","owner":"77358520@N00","secret":"dfa428e6ec","server":"3862","farm":4,"title":"Paris","ispublic":1,"isfriend":0,"isfamily":0,"url_n":"https://farm4.staticflickr.com/3862/14768250614_dfa428e6ec_n.jpg","height_n":212,"width_n":"320"}
];

The above (from the gist) array contains explicit references to the images meant to be displayed. Is there a way to just reference the directory containing said images? It would be impractical, I think, to have to write an array containing a reference for each of, say, a hundred images.

**Comment by garris** [comment]
ok,  Now I understand.  The answer is no.  _Your_ app needs to do that.  

IOW: you would need to write a script which provides the content (JSON) data.  Bear in mind, size dimensions are required -- otherwise TremulaJS would not be able to flow images onto the screen at the correct position (before actually receiving the image).

Hope that makes sense.

**Comment by paxperscientiam** [comment]
That does make sense, garris. I should be able to cobble something together. Thanks again.

**Comment by garris** [comment]
Cheers.
