### ISSUE TITLE
Adding a file name to "main" property in bower.json

### ISSUE THREAD

**Issue by decipher91** [garris/TremulaJS#32]
Hey, can you consider changing

`"main": "dist/"`

in bower.json to

`"main": "./dist/Tremula.min.js"`

In that way this plugin can be properly injected with bower build tools like [wiredep](https://github.com/taptapship/wiredep) which rely on this. I can create a pull request for this. Thanks.

**Comment by garris** [comment]
@decipher91 many apologies for the delayed response -- I have been very very busy with other projects and family.  I have just updated the bower config and pushed a new release.   Best regards.
